POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "alison",
    "email": "alison@vc.com",
    "password": "123456"
}



### login sin conexion a la base de BDD

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "alison",
    "email": "alison@vc.com",
    "password": "123456"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzAxNjc2MTUsImV4cCI6MTczMDE2NzY3NX0.FnjI0h2KDPTtTSVNwEBBZC9PrwZXFukI8K8JInLfuso'
